### PR TITLE
Update CSS and bring up to date with main

### PR DESCRIPTION
**Pull request by johnarban**
This PR merges in main, and simplifies and improves the layout of the AWV component, and makes it more workable on small displays.

### CODE REVIEW

**Comment by patudom** [comment]
This looks really good on my desktop. It has some issues on my phone, but I think we can consider this a "my phone" problem. I don't think it's realistic to display this much information on such a small screen.

It also loads pretty slowly on my phone. The app itself takes ~5-10 seconds to load (with Safari on the slower end), and then opening the AWV takes another 5-10 seconds (although this branch loads a cloud data layer from the get go).

If you think there are small tweaks we can make without too much trouble, here are screenshots of how this looks on my phone.

- The map is so small that if you try to zoom out to see the entire US, the cloud layer has the weird gappy grid.
IMG_9725
- The table info rolls off the side of the screen.
IMG_9724

Possible fixes:
- [ ] Quick: Widen the dimension of the AWV dialog. Maybe just make it 100%.
- [ ] Quick: Slightly reduce font size on mobile throughout the AWV.
- [ ] Less quick: move the % cloud cover scale bar to be horizontally above or below the map.

**Review by patudom — COMMENTED** [review]
See comment above. I think at the least, we can expand the width of the AWV component and try shrinking the font sizes a bit to mitigate the worst of these issues on my phone.

**Comment by johnarban** [comment]
I've fixed a bunch of minor issues, and now it is fullscreen on mobile. i am allowing smaller font-sizes now, by using it's own definition of `--default-font-size`. the minimum value can be varied so that it is large enough but not too large on your phone

**Comment by johnarban** [comment]
I have added a AWV query param that can be used to set some initial state. the idea being that we could share a 'cloud view' link that opens it in the awv-view so people can go directly to it

http://localhost:8080/?awv=true&lat=42&lon=-71

**Pull request merged**
