### PR TITLE
Add query parameter for hiding splash screen

### PR DESCRIPTION
**Pull request by Carifio24**
This PR adds a query parameter for hiding the splash screen as requested in #67. Using a query of `splash=false` (`False` is also accepted) will hide the splash screen.

@patudom Do we want this to hide the intro dialog as well? Currently it does - my thought is that, unless one is working on the intro dialog, it would also be nicer to skip that during development.

### CODE REVIEW

**Comment by patudom** [comment]
I agree, @Carifio24, that we generally want to hide both the splash screen and the intro dialog during development, unless we actively are editing those pages. I think that will automatically happen if `showSplashScreen=true`

**Comment by Carifio24** [comment]
Yeah, this implementation hides the intro dialog as well - the intro dialog is activated when the splash screen is closed, which never happens if we don't show it to begin with.

**Comment by Carifio24** [comment]
@patudom Good catch - I'd forgotten to look at which map was active. I think everything should be working how we want now (include the lat/lon query parameters).

**Comment by patudom** [comment]
Thanks, @Carifio24! I found one more issue - hopefully we'll be good after this. If we open the app with a specific lat/long, we need to override our override to start the location chip at Nazas, DUR, which I'm guessing brings back the weird problem where the first query to mapbox fails.
Screenshot 2024-02-12 at 10 32 59 AM

**Comment by Carifio24** [comment]
@patudom All of those items look good to me.

**Pull request merged**
